# This is a global variable
variables:
    LIBFABRIC_DIR: "/global/cfs/cdirs/m1248/pdc/libfabric-1.12.1/install"
    MERCURY_DIR: "/global/cfs/cdirs/m1248/pdc/mercury-2.0.0/install"
    
stages:
    - build
    #- test

# This stage uses the global SCHEDULER_PARAMETERS variable
build:
    stage: build
    tags:
      - cori
    variables:
        SCHEDULER_PARAMETERS: "-C haswell --qos=debug -N 1 -t 00:30:00 --gres=craynetwork:3"
        # SCHEDULER_PARAMETERS: "--clusters=escori -N 1 --qos=compile -t 00:30:00"
    script:
      - echo "Build PDC"
      # - pwd
      - module list
      - cd src && mkdir build && cd build
      - cmake ../ -DBUILD_MPI_TESTING=ON -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON -DPDC_ENABLE_MPI=ON -DMERCURY_DIR=$MERCURY_DIR -DCMAKE_C_COMPILER=cc -DCMAKE_C_FLAGS=-dynamic -DMPI_RUN_CMD=srun -DPDC_ENABLE_LUSTRE=ON -DPDC_DISABLE_CHECKPOINT=ON
      - make -j
      # - echo "Run Serial Tests"
      # - export LD_LIBRARY_PATH="$LIBFABRIC_DIR/lib:$MERCURY_DIR/lib:$LD_LIBRARY_PATH"
      # - echo $LD_LIBRARY_PATH
      # - ctest -L serial -V
      - echo "Run Parallel Tests"
      - export LD_LIBRARY_PATH="$LIBFABRIC_DIR/lib:$MERCURY_DIR/lib:$LD_LIBRARY_PATH"
      - echo $LD_LIBRARY_PATH
      - ctest -L parallel -V

#test:
#    stage: test
#    tags:
#      - cori
#    variables:
#        SCHEDULER_PARAMETERS: "-C haswell --qos=debug -N 1 -t 00:30:00 --gres=craynetwork:3"
#    script:
#      - echo "PDC Serial Tests"
#      - pwd
#      - export LD_LIBRARY_PATH="$LIBFABRIC_DIR/lib:$MERCURY_DIR/lib:$LD_LIBRARY_PATH"
#      - ctest -L serial

