# This is a global variable
variables:
    # SCHEDULER_PARAMETERS: "--clusters=escori -N 1 --qos=compile -t 01:00:00 --gres=craynetwork:2"
    SCHEDULER_PARAMETERS: "-C haswell --qos=debug -N 1 -t 00:30:00 --gres=craynetwork:2"
    LIBFABRIC_DIR: "/global/cfs/cdirs/m1248/pdc/libfabric/install"
    MERCURY_DIR: "/global/cfs/cdirs/m1248/pdc/mercury/install"
    
stages:
    - build

# This stage uses the global SCHEDULER_PARAMETERS variable
build:
    stage: build
    tags:
      - cori
    script:
      - echo "Build PDC"
      # - pwd
      - module list
      - cd src && mkdir build && cd build
      - cmake ../ -DBUILD_MPI_TESTING=ON -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON -DPDC_ENABLE_MPI=ON -DMERCURY_DIR=$MERCURY_DIR -DCMAKE_C_COMPILER=cc -DCMAKE_C_FLAGS=-dynamic -DMPI_RUN_CMD=srun
      - make -j
      - echo "Run Parallel Tests"
      - export LD_LIBRARY_PATH="$LIBFABRIC_DIR/lib:$MERCURY_DIR/lib:$LD_LIBRARY_PATH"
      # - echo $LD_LIBRARY_PATH
      - ctest -L parallel
